# Generated by Django 6.0 on 2026-01-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
